# Generated by Django 4.0.2 on 2022-02-18 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrehusUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя орехуса')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='OrehusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=50, verbose_name='Комментарий')),
                ('operation', models.IntegerField(verbose_name='Сколько прибавили')),
                ('datetime_comment', models.DateTimeField(auto_now_add=True, verbose_name='Время комментария')),
                ('orehus_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='nuts.orehususers', verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Изменение рейтинга',
                'verbose_name_plural': 'Изменение рейтинга',
            },
        ),
    ]
