# Generated by Django 4.0.2 on 2022-03-22 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orehuschange',
            options={'ordering': ['-datetime_comment'], 'verbose_name': 'Изменение рейтинга', 'verbose_name_plural': 'Изменение рейтинга'},
        ),
        migrations.AlterModelOptions(
            name='orehususers',
            options={'ordering': ['-rating'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='orehuschange',
            name='who_changed',
            field=models.CharField(max_length=20, null=True, verbose_name='Кто?'),
        ),
        migrations.AlterField(
            model_name='orehuschange',
            name='comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='orehuschange',
            name='operation',
            field=models.IntegerField(verbose_name='Сколько прибавиляем?'),
        ),
        migrations.AlterField(
            model_name='orehuschange',
            name='orehus_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='nuts.orehususers', verbose_name='Кому прибавляем?'),
        ),
    ]
