# Generated by Django 4.0.2 on 2022-03-22 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuts', '0004_alter_customuser_bio_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-rating']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, default='2000-09-26'),
        ),
        migrations.AlterField(
            model_name='orehuschange',
            name='orehus_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кому прибавляем?'),
        ),
    ]
