# Generated by Django 4.0.2 on 2022-03-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuts', '0006_delete_orehususers_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orehuschange',
            name='rating_new',
            field=models.IntegerField(null=True, verbose_name='Сколько стало'),
        ),
        migrations.AddField(
            model_name='orehuschange',
            name='rating_was',
            field=models.IntegerField(null=True, verbose_name='Сколько было'),
        ),
    ]
