# Generated by Django 4.0.2 on 2022-03-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuts', '0007_orehuschange_rating_new_orehuschange_rating_was'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unchanged_name',
            field=models.TextField(default=1, max_length=20, verbose_name='Неизменяемое имя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orehuschange',
            name='who_changed',
            field=models.CharField(default=2, max_length=20, verbose_name='Кто прибавляет?'),
            preserve_default=False,
        ),
    ]
