# Generated by Django 4.0.2 on 2022-03-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuts', '0008_customuser_unchanged_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_vk_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_zodiac_sign',
            field=models.ImageField(blank=True, null=True, upload_to='zodiac_sign/%Y/%m/%d/', verbose_name='Иконка'),
        ),
    ]
