# Generated by Django 4.0.2 on 2022-03-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuts', '0009_customuser_user_img_customuser_user_vk_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_zodiac_sign',
            field=models.ImageField(blank=True, null=True, upload_to='zodiac_sign/', verbose_name='Иконка'),
        ),
    ]
