# Generated by Django 4.0.2 on 2022-03-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuts', '0011_remove_customuser_user_zodiac_sign'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserZodiacSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_zodiac_sign_img', models.ImageField(blank=True, null=True, upload_to='zodiac_sign/', verbose_name='Иконка')),
                ('user_zodiac', models.CharField(max_length=20)),
            ],
        ),
    ]
