# Generated by Django 4.0.2 on 2022-03-27 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuts', '0012_userzodiacsign'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_zodiac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='nuts.userzodiacsign', verbose_name='Знак зодиака'),
            preserve_default=False,
        ),
    ]
