# Generated by Django 5.0.3 on 2024-04-01 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuts', '0014_alter_userzodiacsign_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=300, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_zodiac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nuts.userzodiacsign', verbose_name='Знак зодиака'),
        ),
        migrations.AlterField(
            model_name='orehuschange',
            name='operation',
            field=models.IntegerField(verbose_name='Сколько прибавляем?'),
        ),
    ]
