# Generated by Django 5.0.3 on 2024-04-01 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuts', '0016_alter_customuser_user_zodiac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_zodiac',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nuts.userzodiacsign', verbose_name='Знак зодиака'),
        ),
    ]
