# Generated by Django 5.0.3 on 2024-04-01 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuts', '0017_alter_customuser_user_zodiac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orehuschange',
            name='orehus_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кому прибавляем?'),
        ),
    ]
